    - name: Build & push
      run: |
        docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
    - name: Deploy to Fly
      uses: superfly/flyctl-actions@v2
      with:
        args: "deploy --image ghcr.io/${{ github.repository }}:${{ github.sha }}"
        secrets: FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }}
