# ◇ CODEX_IMPLEMENT: add auto-merge workflow
name: Auto-Merge Trivial Codex PRs
on:
  pull_request:
jobs:
  automerge:
    if: github.event.pull_request.title startsWith 'Codex auto-impl'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge PR
        run: gh pr merge ${{ github.event.pull_request.number }} --squash --auto

