name: hybrid-seed-bench
on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install -e .[ci]
          python -m pip install orjson
      - name: Run sweep
        run: python bench/hybrid_seed.py > hybrid.csv
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: hybrid-seed-${{ github.run_number }}-${{ github.run_attempt }}
          path: hybrid.csv
          retention-days: 7
