name: smoke-sim
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke-sim:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        tuner: [bandit]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: |
          python -m pip install -e .[ci]
      - name: Run smoke simulation
        env:
          NODE_KEY: smoke
        run: TUNER=${{ matrix.tuner }} bash scripts/smoke_run.sh
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # ensure unique name per matrix leg and retry
          name: smoke-${{ matrix.tuner }}-${{ github.run_number }}-${{ github.run_attempt }}
          path: artifacts/
          retention-days: 7
